version: '3.8'

services:
  ky-spider:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped